wandb_version: 1

entity:
  desc: null
  value: ighina251
project:
  desc: null
  value: ClimateNLP2024
key:
  desc: null
  value: 12161268c20c86bf7bcf69dd0d56e167e17b2102
job_type:
  desc: null
  value: evaluate
tags:
  desc: null
  value:
  - summarization
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710509261.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.16.4
      6: 4.26.0
      8:
      - 5
      13: linux-x86_64
